Fix incompatibilities with PCRE 8.32 in the BackportedTranslator class
contao-community-alliance/translator pull request #10
Opened 2019-11-19 15:13 UTC by plorenz-etes

Due to a regression in PCRE 8.32 there is a problem using the translator on systems using this version of the library. Some regular expressions can't be parsed which breaks functionality. As a result, e.g. using MetaModels isn't possible because every translation returned has the value 'Array'.

In Contao 4.5, the Translator class was introduced and ran into this problem: https://github.com/contao/contao/issues/886
Since the BackportedTranslator class in this project uses parts of the code from the original Contao Translator class, I think the changes made here to Translator.php should also be made to the BackportedTranslator class: https://github.com/contao/contao/pull/916

Changing these two lines in a test installation environment fixes the problem instantly for me.

2019-11-19 15:18 UTC, baumannsven commented
@plorenz-etes Can you post the translation to use? So we can wrote a test for this problem.

2019-11-20 08:04 UTC, plorenz-etes commented
@baumannsven It basically happens with any translation. The following code will be executed when looking up a translation (BackportedTranslator.php lines 128/129):

```
preg_match_all('/(?:\\\\[\\\\.]|[^.])++/', $id, $matches);
$parts = preg_replace('/\\\\([\\\\.])/', '$1', $matches[0]);
```

Since those regular expressions aren't correct for PCRE 8.32, they can't be compiled and thus, the function `getFromGlobals()` doesn't return a string but rather the complete language array `$_GLOBALS['TL_LANG']`.

2019-11-21 14:17 UTC, discordier commented
IMO the lines from Contao core can be used along the corresponding unit tests, see commit https://github.com/contao/contao/pull/916/commits/75c5d8c216b2910e7b260d1b4dd256ad72e529a7

2019-11-21 14:20 UTC, baumannsven commented
@discordier Thanks.

2019-12-03 14:38 UTC, plorenz-etes commented
Hi, sorry to ask but since we've got a customer running into this problem - can you tell whether this PR will make it into the next release?

2019-12-05 16:41 UTC, discordier commented
It will as long as the tests are ported as well and the build runs successfully.

Sadly no one of our team has currently the time to port them over, so it would be nice if you could update your PR.

As soon all is green, we will be happy to merge.

2019-12-20 08:20 UTC, zonky2 commented
@plorenz-etes please add your name and email as author - see check in travis...

2019-12-20 09:11 UTC, plorenz-etes commented
@zonky2 Thank you for the reminder - I have added the requested author line.

2019-12-20 09:14 UTC, zonky2 commented
thx!

2019-12-20 15:32 UTC, discordier commented
The tests are still missing?

2019-12-20 19:52 UTC, discordier requested changes
Tests still missing, therefore still a NACK from me.

2026-03-09 17:32 UTC, closed without merging